package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"sort"
	"strings"
)

type Option struct {
	Name      string
	FieldName string
	Shorthand string
	Usage     string
	Type      string
	Default   string
}

func main() {
	// Registry is in the same directory as where we are called from go:generate
	options, err := parseRegistry("registry.go")
	if err != nil {
		// Fallback for manual run from root
		options, err = parseRegistry("internal/config/registry.go")
		if err != nil {
			log.Fatalf("failed to parse registry: %v", err)
		}
	}

	// Paths relative to project root (manual or via go generate)
	prefix := ""
	if _, err := os.Stat("internal/config"); err != nil {
		prefix = "../../"
	}

	if err := generateCLIOptions(prefix+"internal/config/cli_options_gen.go", options); err != nil {
		log.Fatalf("failed to generate CLIOptions: %v", err)
	}

	if err := generateRootOptions(prefix+"internal/command/root_options_gen.go", options); err != nil {
		log.Fatalf("failed to generate rootOptions: %v", err)
	}

	if err := generateFlags(prefix+"internal/command/flags_gen.go", options); err != nil {
		log.Fatalf("failed to generate flags: %v", err)
	}
}

func parseRegistry(path string) (map[string][]Option, error) {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}

	res := make(map[string][]Option)

	for _, decl := range node.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.VAR {
			continue
		}

		for _, spec := range genDecl.Specs {
			valueSpec, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}

			for i, name := range valueSpec.Names {
				if !strings.HasSuffix(name.Name, "Options") {
					continue
				}
				optionType := strings.TrimSuffix(name.Name, "Options")
				if i >= len(valueSpec.Values) {
					continue
				}

				lit, ok := valueSpec.Values[i].(*ast.CompositeLit)
				if !ok {
					continue
				}

				var options []Option
				for _, elt := range lit.Elts {
					elem, ok := elt.(*ast.CompositeLit)
					if !ok {
						continue
					}

					opt := Option{Type: optionType}
					for _, kvExpr := range elem.Elts {
						kv, ok := kvExpr.(*ast.KeyValueExpr)
						if !ok {
							continue
						}
						key := kv.Key.(*ast.Ident).Name
						val := ""
						switch v := kv.Value.(type) {
						case *ast.BasicLit:
							val = strings.Trim(v.Value, "\"")
						case *ast.Ident:
							val = v.Name
						}

						switch key {
						case "Name":
							opt.Name = val
						case "FieldName":
							opt.FieldName = val
						case "Shorthand":
							opt.Shorthand = val
						case "Usage":
							opt.Usage = val
						case "Default":
							opt.Default = val
						}
					}
					if opt.FieldName == "" {
						opt.FieldName = PascalCase(opt.Name)
					}
					options = append(options, opt)
				}
				res[optionType] = options
			}
		}
	}

	return res, nil
}

var initialisms = map[string]string{
	"tty":  "TTY",
	"dns":  "DNS",
	"cpus": "CPUs",
}

func PascalCase(s string) string {
	var builder strings.Builder
	for _, part := range strings.Split(s, "-") {
		if part == "" {
			continue
		}
		if val, ok := initialisms[strings.ToLower(part)]; ok {
			builder.WriteString(val)
			continue
		}
		builder.WriteString(strings.ToUpper(part[0:1]))
		builder.WriteString(part[1:])
	}
	return builder.String()
}

func generateCLIOptions(path string, options map[string][]Option) error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by scripts/gen-options.go. DO NOT EDIT.\n\n")
	buf.WriteString("package config\n\n")
	buf.WriteString("// CLIOptions represents values from CLI flags.\n")
	buf.WriteString("type CLIOptions struct {\n")

	keys := []string{"String", "Bool", "Int", "Float64", "StringSlice"}
	for _, k := range keys {
		for _, opt := range options[k] {
			goType := ""
			switch k {
			case "String":
				goType = "*string"
			case "Bool":
				goType = "*bool"
			case "Int":
				goType = "*int"
			case "Float64":
				goType = "*float64"
			case "StringSlice":
				goType = "[]string"
			}
			buf.WriteString(fmt.Sprintf("\t%s %s\n", opt.FieldName, goType))
			buf.WriteString(fmt.Sprintf("\tCderun%s %s\n", opt.FieldName, goType))
		}
	}
	buf.WriteString("}\n")

	return writeFileIfChanged(path, buf.Bytes())
}

func generateRootOptions(path string, options map[string][]Option) error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by scripts/gen-options.go. DO NOT EDIT.\n\n")
	buf.WriteString("package command\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"cderun/internal/config\"\n")
	buf.WriteString("\t\"github.com/spf13/cobra\"\n")
	buf.WriteString(")\n\n")

	buf.WriteString("type rootOptionsGen struct {\n")
	keys := []string{"String", "Bool", "Int", "Float64", "StringSlice"}
	for _, k := range keys {
		for _, opt := range options[k] {
			goType := ""
			switch k {
			case "String":
				goType = "string"
			case "Bool":
				goType = "bool"
			case "Int":
				goType = "int"
			case "Float64":
				goType = "float64"
			case "StringSlice":
				goType = "[]string"
			}
			buf.WriteString(fmt.Sprintf("\t%s %s\n", strings.ToLower(opt.FieldName[:1])+opt.FieldName[1:], goType))
			buf.WriteString(fmt.Sprintf("\tcderun%s %s\n", opt.FieldName, goType))
		}
	}
	buf.WriteString("}\n\n")

	buf.WriteString("func (o *rootOptions) populateCLIOptions(cmd *cobra.Command) config.CLIOptions {\n")
	buf.WriteString("\treturn config.CLIOptions{\n")
	for _, k := range keys {
		for _, opt := range options[k] {
			lowerName := strings.ToLower(opt.FieldName[:1]) + opt.FieldName[1:]
			if k == "StringSlice" {
				buf.WriteString(fmt.Sprintf("\t\t%s: o.%s,\n", opt.FieldName, lowerName))
				buf.WriteString(fmt.Sprintf("\t\tCderun%s: o.cderun%s,\n", opt.FieldName, opt.FieldName))
			} else {
				buf.WriteString(fmt.Sprintf("\t\t%s: opt(cmd.Flags().Changed(%q), o.%s),\n", opt.FieldName, opt.Name, lowerName))
				buf.WriteString(fmt.Sprintf("\t\tCderun%s: opt(cmd.Flags().Changed(%q), o.cderun%s),\n", opt.FieldName, "cderun-"+opt.Name, opt.FieldName))
			}
		}
	}
	buf.WriteString("\t}\n")
	buf.WriteString("}\n")

	return writeFileIfChanged(path, buf.Bytes())
}

func generateFlags(path string, options map[string][]Option) error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by scripts/gen-options.go. DO NOT EDIT.\n\n")
	buf.WriteString("package command\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"github.com/spf13/cobra\"\n")
	buf.WriteString(")\n\n")

	buf.WriteString("func registerFlags(cmd *cobra.Command, o *rootOptions) {\n")
	buf.WriteString("\tf := cmd.PersistentFlags()\n")

	// Helper to get sortable keys
	type optWithType struct {
		Option
		Kind string
	}
	var allOpts []optWithType
	for _, k := range []string{"String", "Bool", "Int", "Float64", "StringSlice"} {
		for _, opt := range options[k] {
			allOpts = append(allOpts, optWithType{opt, k})
		}
	}
	// Sort by name to have deterministic output
	sort.Slice(allOpts, func(i, j int) bool {
		return allOpts[i].Name < allOpts[j].Name
	})

	for _, owt := range allOpts {
		opt := owt.Option
		k := owt.Kind
		lowerName := strings.ToLower(opt.FieldName[:1]) + opt.FieldName[1:]
		p1Name := "cderun" + opt.FieldName
		p2Name := opt.Name
		p1FlagName := "cderun-" + opt.Name

		p2Short := ""
		if opt.Shorthand != "" {
			p2Short = fmt.Sprintf(", %q", opt.Shorthand)
		}

		switch k {
		case "String":
			defVal := fmt.Sprintf("%q", opt.Default)
			if p2Short != "" {
				buf.WriteString(fmt.Sprintf("\tf.StringVarP(&o.%s, %q%s, %s, %q)\n", lowerName, p2Name, p2Short, defVal, opt.Usage))
			} else {
				buf.WriteString(fmt.Sprintf("\tf.StringVar(&o.%s, %q, %s, %q)\n", lowerName, p2Name, defVal, opt.Usage))
			}
			buf.WriteString(fmt.Sprintf("\tf.StringVar(&o.%s, %q, %q, %q)\n", p1Name, p1FlagName, "", "Override "+p2Name+" setting"))
		case "Bool":
			defVal := "false"
			if opt.Default == "true" {
				defVal = "true"
			}
			if p2Short != "" {
				buf.WriteString(fmt.Sprintf("\tf.BoolVarP(&o.%s, %q%s, %s, %q)\n", lowerName, p2Name, p2Short, defVal, opt.Usage))
			} else {
				buf.WriteString(fmt.Sprintf("\tf.BoolVar(&o.%s, %q, %s, %q)\n", lowerName, p2Name, defVal, opt.Usage))
			}
			buf.WriteString(fmt.Sprintf("\tf.BoolVar(&o.%s, %q, %s, %q)\n", p1Name, p1FlagName, defVal, "Override "+p2Name+" setting"))
		case "Int":
			defVal := opt.Default
			if defVal == "" {
				defVal = "0"
			}
			if p2Short != "" {
				buf.WriteString(fmt.Sprintf("\tf.IntVarP(&o.%s, %q%s, %s, %q)\n", lowerName, p2Name, p2Short, defVal, opt.Usage))
			} else {
				buf.WriteString(fmt.Sprintf("\tf.IntVar(&o.%s, %q, %s, %q)\n", lowerName, p2Name, defVal, opt.Usage))
			}
			buf.WriteString(fmt.Sprintf("\tf.IntVar(&o.%s, %q, 0, %q)\n", p1Name, p1FlagName, "Override "+p2Name+" setting"))
		case "Float64":
			defVal := opt.Default
			if defVal == "" {
				defVal = "0"
			}
			if p2Short != "" {
				buf.WriteString(fmt.Sprintf("\tf.Float64VarP(&o.%s, %q%s, %s, %q)\n", lowerName, p2Name, p2Short, defVal, opt.Usage))
			} else {
				buf.WriteString(fmt.Sprintf("\tf.Float64Var(&o.%s, %q, %s, %q)\n", lowerName, p2Name, defVal, opt.Usage))
			}
			buf.WriteString(fmt.Sprintf("\tf.Float64Var(&o.%s, %q, 0, %q)\n", p1Name, p1FlagName, "Override "+p2Name+" setting"))
		case "StringSlice":
			if p2Short != "" {
				buf.WriteString(fmt.Sprintf("\tf.StringArrayVarP(&o.%s, %q%s, nil, %q)\n", lowerName, p2Name, p2Short, opt.Usage))
			} else {
				buf.WriteString(fmt.Sprintf("\tf.StringArrayVar(&o.%s, %q, nil, %q)\n", lowerName, p2Name, opt.Usage))
			}
			buf.WriteString(fmt.Sprintf("\tf.StringArrayVar(&o.%s, %q, nil, %q)\n", p1Name, p1FlagName, "Override "+p2Name+" setting"))
		}
	}
	buf.WriteString("}\n")

	return writeFileIfChanged(path, buf.Bytes())
}

func writeFileIfChanged(path string, content []byte) error {
	formatted, err := format.Source(content)
	if err != nil {
		fmt.Printf("Warning: failed to format %s: %v\n", path, err)
		formatted = content
	}

	existing, err := os.ReadFile(path)
	if err == nil && bytes.Equal(existing, formatted) {
		return nil
	}

	return os.WriteFile(path, formatted, 0644)
}
