package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"slices"
	"strings"
	"text/template"

	"cderun/internal/config"
)

type OptionData struct {
	Name        string
	FieldName   string
	VarName     string
	OverrideVar string
	Type        string // "bool", "string", "int", "float64", "[]string"
	Shorthand   string
	Usage       string
	Default     string // Go expression
}

func varName(name, fieldName string) string {
	if fieldName == "" {
		fieldName = config.PascalCase(name)
	}
	if fieldName == "TTY" {
		return "tty"
	}
	if fieldName == "DNS" {
		return "dns"
	}
	if fieldName == "CPUs" {
		return "cpus"
	}
	return strings.ToLower(fieldName[0:1]) + fieldName[1:]
}

func overrideVarName(name, fieldName string) string {
	if fieldName == "" {
		fieldName = config.PascalCase(name)
	}
	return "cderun" + fieldName
}

func main() {
	var options []OptionData

	for _, opt := range config.BoolOptions {
		fName := opt.FieldName
		if fName == "" {
			fName = config.PascalCase(opt.Name)
		}
		options = append(options, OptionData{
			Name:        opt.Name,
			FieldName:   fName,
			VarName:     varName(opt.Name, fName),
			OverrideVar: overrideVarName(opt.Name, fName),
			Type:        "bool",
			Shorthand:   opt.Shorthand,
			Usage:       opt.Usage,
			Default:     fmt.Sprintf("%t", opt.Default),
		})
	}

	for _, opt := range config.StringOptions {
		fName := opt.FieldName
		if fName == "" {
			fName = config.PascalCase(opt.Name)
		}
		options = append(options, OptionData{
			Name:        opt.Name,
			FieldName:   fName,
			VarName:     varName(opt.Name, fName),
			OverrideVar: overrideVarName(opt.Name, fName),
			Type:        "string",
			Shorthand:   opt.Shorthand,
			Usage:       opt.Usage,
			Default:     fmt.Sprintf("%q", opt.Default),
		})
	}

	for _, opt := range config.IntOptions {
		fName := opt.FieldName
		if fName == "" {
			fName = config.PascalCase(opt.Name)
		}
		options = append(options, OptionData{
			Name:        opt.Name,
			FieldName:   fName,
			VarName:     varName(opt.Name, fName),
			OverrideVar: overrideVarName(opt.Name, fName),
			Type:        "int",
			Shorthand:   opt.Shorthand,
			Usage:       opt.Usage,
			Default:     fmt.Sprintf("%d", opt.Default),
		})
	}

	for _, opt := range config.Float64Options {
		fName := opt.FieldName
		if fName == "" {
			fName = config.PascalCase(opt.Name)
		}
		options = append(options, OptionData{
			Name:        opt.Name,
			FieldName:   fName,
			VarName:     varName(opt.Name, fName),
			OverrideVar: overrideVarName(opt.Name, fName),
			Type:        "float64",
			Shorthand:   opt.Shorthand,
			Usage:       opt.Usage,
			Default:     fmt.Sprintf("%f", opt.Default),
		})
	}

	for _, opt := range config.StringSliceOptions {
		fName := opt.FieldName
		if fName == "" {
			fName = config.PascalCase(opt.Name)
		}
		options = append(options, OptionData{
			Name:        opt.Name,
			FieldName:   fName,
			VarName:     varName(opt.Name, fName),
			OverrideVar: overrideVarName(opt.Name, fName),
			Type:        "[]string",
			Shorthand:   opt.Shorthand,
			Usage:       opt.Usage,
			Default:     "nil",
		})
	}

	slices.SortFunc(options, func(a, b OptionData) int {
		return strings.Compare(a.Name, b.Name)
	})

	if err := generateCLIOptions(options); err != nil {
		fmt.Fprintf(os.Stderr, "Error generating CLIOptions: %v\n", err)
		os.Exit(1)
	}

	if err := generateRootFlags(options); err != nil {
		fmt.Fprintf(os.Stderr, "Error generating RootFlags: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Code generation of options completed successfully.")
}

func generateCLIOptions(options []OptionData) error {
	var buf bytes.Buffer
	tmpl := `// Code generated by scripts/gen_options.go; DO NOT EDIT.

package config

// CLIOptions represents values from CLI flags.
type CLIOptions struct {
{{- range .}}
	{{.FieldName}} {{if eq .Type "[]string"}}{{.Type}}{{else}}*{{.Type}}{{end}}
	Cderun{{.FieldName}} {{if eq .Type "[]string"}}{{.Type}}{{else}}*{{.Type}}{{end}}
{{- end}}
}
`
	t := template.Must(template.New("cli_options").Parse(tmpl))
	if err := t.Execute(&buf, options); err != nil {
		return err
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("failed to format CLIOptions source: %w. Raw:\n%s", err, buf.String())
	}

	//nolint:gosec // 0644 is intentional for standard generated options files
	return os.WriteFile("internal/config/cli_options.gen.go", formatted, 0644)
}

func generateRootFlags(options []OptionData) error {
	var buf bytes.Buffer
	tmpl := `// Code generated by scripts/gen_options.go; DO NOT EDIT.

package command

import (
	"github.com/spf13/cobra"
	"cderun/internal/config"
)

// rootFlags contains fields bound to cobra flag definitions.
type rootFlags struct {
{{- range .}}
	{{.VarName}} {{.Type}}
	{{.OverrideVar}} {{.Type}}
{{- end}}
}

// buildCLIOptions dynamically builds and populates config.CLIOptions from command flags.
func buildCLIOptions(cmd *cobra.Command, o *rootOptions) config.CLIOptions {
	optBool := func(changed bool, v bool) *bool {
		if !changed {
			return nil
		}
		return &v
	}
	optStr := func(changed bool, v string) *string {
		if !changed {
			return nil
		}
		return &v
	}
	optInt := func(changed bool, v int) *int {
		if !changed {
			return nil
		}
		return &v
	}
	optFloat := func(changed bool, v float64) *float64 {
		if !changed {
			return nil
		}
		return &v
	}

	return config.CLIOptions{
{{- range .}}
	{{- if eq .Type "bool"}}
		{{.FieldName}}: optBool(cmd.Flags().Changed("{{.Name}}"), o.{{.VarName}}),
		Cderun{{.FieldName}}: optBool(cmd.Flags().Changed("cderun-{{.Name}}"), o.{{.OverrideVar}}),
	{{- else if eq .Type "string"}}
		{{.FieldName}}: optStr(cmd.Flags().Changed("{{.Name}}"), o.{{.VarName}}),
		Cderun{{.FieldName}}: optStr(cmd.Flags().Changed("cderun-{{.Name}}"), o.{{.OverrideVar}}),
	{{- else if eq .Type "int"}}
		{{.FieldName}}: optInt(cmd.Flags().Changed("{{.Name}}"), o.{{.VarName}}),
		Cderun{{.FieldName}}: optInt(cmd.Flags().Changed("cderun-{{.Name}}"), o.{{.OverrideVar}}),
	{{- else if eq .Type "float64"}}
		{{.FieldName}}: optFloat(cmd.Flags().Changed("{{.Name}}"), o.{{.VarName}}),
		Cderun{{.FieldName}}: optFloat(cmd.Flags().Changed("cderun-{{.Name}}"), o.{{.OverrideVar}}),
	{{- else if eq .Type "[]string"}}
		{{.FieldName}}: o.{{.VarName}},
		Cderun{{.FieldName}}: o.{{.OverrideVar}},
	{{- end}}
{{- end}}
	}
}

func getBoolPointers(o *rootOptions, name string) (base, override *bool) {
	switch name {
{{- range .}}
	{{- if eq .Type "bool"}}
	case "{{.Name}}":
		return &o.{{.VarName}}, &o.{{.OverrideVar}}
	{{- end}}
{{- end}}
	default:
		return nil, nil
	}
}

func getStringPointers(o *rootOptions, name string) (base, override *string) {
	switch name {
{{- range .}}
	{{- if eq .Type "string"}}
	case "{{.Name}}":
		return &o.{{.VarName}}, &o.{{.OverrideVar}}
	{{- end}}
{{- end}}
	default:
		return nil, nil
	}
}

func getIntPointers(o *rootOptions, name string) (base, override *int) {
	switch name {
{{- range .}}
	{{- if eq .Type "int"}}
	case "{{.Name}}":
		return &o.{{.VarName}}, &o.{{.OverrideVar}}
	{{- end}}
{{- end}}
	default:
		return nil, nil
	}
}

func getFloat64Pointers(o *rootOptions, name string) (base, override *float64) {
	switch name {
{{- range .}}
	{{- if eq .Type "float64"}}
	case "{{.Name}}":
		return &o.{{.VarName}}, &o.{{.OverrideVar}}
	{{- end}}
{{- end}}
	default:
		return nil, nil
	}
}

func getStringSlicePointers(o *rootOptions, name string) (base, override *[]string) {
	switch name {
{{- range .}}
	{{- if eq .Type "[]string"}}
	case "{{.Name}}":
		return &o.{{.VarName}}, &o.{{.OverrideVar}}
	{{- end}}
{{- end}}
	default:
		return nil, nil
	}
}
`
	t := template.Must(template.New("root_flags").Parse(tmpl))
	if err := t.Execute(&buf, options); err != nil {
		return err
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("failed to format RootFlags source: %w. Raw:\n%s", err, buf.String())
	}

	//nolint:gosec // 0644 is intentional for standard generated options files
	return os.WriteFile("internal/command/root_flags.gen.go", formatted, 0644)
}
