package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"sort"
	"strings"
)

type Option struct {
	Name      string
	FieldName string
	Shorthand string
	Usage     string
	Default   string
	Type      string // "int", "float64", "string", "[]string", "bool"
}

func main() {
	registryPath := "internal/config/registry.go"
	if _, err := os.Stat(registryPath); err != nil {
		registryPath = "registry.go"
	}

	options, err := parseRegistry(registryPath)
	if err != nil {
		log.Fatalf("failed to parse registry: %v", err)
	}

	if err := generateConfigOptions(options); err != nil {
		log.Fatalf("failed to generate config options: %v", err)
	}

	if err := generateCommandOptions(options); err != nil {
		log.Fatalf("failed to generate command options: %v", err)
	}
}

func parseRegistry(filename string) ([]Option, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, filename, nil, 0)
	if err != nil {
		return nil, err
	}

	var options []Option

	for _, decl := range f.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.VAR {
			continue
		}

		for _, spec := range gen.Specs {
			vspec, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}

			for _, name := range vspec.Names {
				var optType string
				switch name.Name {
				case "StringOptions":
					optType = "string"
				case "BoolOptions":
					optType = "bool"
				case "IntOptions":
					optType = "int"
				case "Float64Options":
					optType = "float64"
				case "StringSliceOptions":
					optType = "[]string"
				default:
					continue
				}

				for _, val := range vspec.Values {
					cl, ok := val.(*ast.CompositeLit)
					if !ok {
						continue
					}

					for _, elt := range cl.Elts {
						eltCl, ok := elt.(*ast.CompositeLit)
						if !ok {
							continue
						}

						opt := Option{Type: optType}
						for _, kv := range eltCl.Elts {
							kve, ok := kv.(*ast.KeyValueExpr)
							if !ok {
								continue
							}

							key := kve.Key.(*ast.Ident).Name
							valStr := ""

							switch v := kve.Value.(type) {
							case *ast.BasicLit:
								valStr = strings.Trim(v.Value, "\"")
							case *ast.Ident:
								valStr = v.Name
							}

							switch key {
							case "Name":
								opt.Name = valStr
							case "FieldName":
								opt.FieldName = valStr
							case "Shorthand":
								opt.Shorthand = valStr
							case "Usage":
								opt.Usage = valStr
							case "Default":
								opt.Default = valStr
							}
						}

						if opt.FieldName == "" {
							opt.FieldName = PascalCase(opt.Name)
						}
						options = append(options, opt)
					}
				}
			}
		}
	}

	return options, nil
}

func generateConfigOptions(options []Option) error {
	outPath := "internal/config/options_gen.go"
	pkg := "config"
	if _, err := os.Stat("internal/config"); err != nil {
		outPath = "options_gen.go"
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by genflags.go. DO NOT EDIT.\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", pkg))
	buf.WriteString("// CLIOptions represents values from CLI flags.\n")
	buf.WriteString("type CLIOptions struct {\n")

	sort.Slice(options, func(i, j int) bool {
		return options[i].FieldName < options[j].FieldName
	})

	for _, opt := range options {
		typeName := opt.Type
		if opt.Type != "[]string" {
			typeName = "*" + opt.Type
		}
		buf.WriteString(fmt.Sprintf("\t%s %s\n", opt.FieldName, typeName))
		buf.WriteString(fmt.Sprintf("\tCderun%s %s\n", opt.FieldName, typeName))
	}
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}

	return os.WriteFile(outPath, formatted, 0644)
}

func generateCommandOptions(options []Option) error {
	outPath := "internal/command/options_gen.go"
	if _, err := os.Stat("internal/command"); err != nil {
		outPath = "options_gen.go"
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by genflags.go. DO NOT EDIT.\n")
	buf.WriteString("package command\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"cderun/internal/config\"\n")
	buf.WriteString("\t\"github.com/spf13/cobra\"\n")
	buf.WriteString(")\n\n")

	buf.WriteString("// flagOptions contains plain types for Cobra binding.\n")
	buf.WriteString("type flagOptions struct {\n")
	for _, opt := range options {
		buf.WriteString(fmt.Sprintf("\t%s %s\n", opt.FieldName, opt.Type))
		buf.WriteString(fmt.Sprintf("\tCderun%s %s\n", opt.FieldName, opt.Type))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("func (o *rootOptions) registerFlags(cmd *cobra.Command) {\n")
	buf.WriteString("\tf := cmd.PersistentFlags()\n")
	for _, opt := range options {
		p2Name := opt.Name
		p1Name := "cderun-" + opt.Name
		p2Short := opt.Shorthand
		p2Usage := opt.Usage
		p1Usage := fmt.Sprintf("Override %s setting (highest priority, can be used after subcommand)", p2Name)
		p2Field := "&o." + opt.FieldName
		p1Field := "&o.Cderun" + opt.FieldName

		switch opt.Type {
		case "bool":
			def := opt.Default
			if def == "" {
				def = "false"
			}
			if p2Short != "" {
				buf.WriteString(fmt.Sprintf("\tf.BoolVarP(%s, %q, %q, %s, %q)\n", p2Field, p2Name, p2Short, def, p2Usage))
			} else {
				buf.WriteString(fmt.Sprintf("\tf.BoolVar(%s, %q, %s, %q)\n", p2Field, p2Name, def, p2Usage))
			}
			buf.WriteString(fmt.Sprintf("\tf.BoolVar(%s, %q, %s, %q)\n", p1Field, p1Name, def, p1Usage))
		case "string":
			def := fmt.Sprintf("%q", opt.Default)
			if p2Short != "" {
				buf.WriteString(fmt.Sprintf("\tf.StringVarP(%s, %q, %q, %s, %q)\n", p2Field, p2Name, p2Short, def, p2Usage))
			} else {
				buf.WriteString(fmt.Sprintf("\tf.StringVar(%s, %q, %s, %q)\n", p2Field, p2Name, def, p2Usage))
			}
			buf.WriteString(fmt.Sprintf("\tf.StringVar(%s, %q, \"\", %q)\n", p1Field, p1Name, p1Usage))
		case "int":
			def := opt.Default
			if def == "" {
				def = "0"
			}
			if p2Short != "" {
				buf.WriteString(fmt.Sprintf("\tf.IntVarP(%s, %q, %q, %s, %q)\n", p2Field, p2Name, p2Short, def, p2Usage))
			} else {
				buf.WriteString(fmt.Sprintf("\tf.IntVar(%s, %q, %s, %q)\n", p2Field, p2Name, def, p2Usage))
			}
			buf.WriteString(fmt.Sprintf("\tf.IntVar(%s, %q, 0, %q)\n", p1Field, p1Name, p1Usage))
		case "float64":
			def := opt.Default
			if def == "" {
				def = "0"
			}
			if p2Short != "" {
				buf.WriteString(fmt.Sprintf("\tf.Float64VarP(%s, %q, %q, %s, %q)\n", p2Field, p2Name, p2Short, def, p2Usage))
			} else {
				buf.WriteString(fmt.Sprintf("\tf.Float64Var(%s, %q, %s, %q)\n", p2Field, p2Name, def, p2Usage))
			}
			buf.WriteString(fmt.Sprintf("\tf.Float64Var(%s, %q, 0, %q)\n", p1Field, p1Name, p1Usage))
		case "[]string":
			if p2Short != "" {
				buf.WriteString(fmt.Sprintf("\tf.StringArrayVarP(%s, %q, %q, nil, %q)\n", p2Field, p2Name, p2Short, p2Usage))
			} else {
				buf.WriteString(fmt.Sprintf("\tf.StringArrayVar(%s, %q, nil, %q)\n", p2Field, p2Name, p2Usage))
			}
			buf.WriteString(fmt.Sprintf("\tf.StringArrayVar(%s, %q, nil, %q)\n", p1Field, p1Name, p1Usage))
		}
	}
	buf.WriteString("}\n\n")

	buf.WriteString("func (o *rootOptions) buildCLIOptions(cmd *cobra.Command) config.CLIOptions {\n")
	buf.WriteString("\treturn config.CLIOptions{\n")
	for _, opt := range options {
		if opt.Type == "[]string" {
			buf.WriteString(fmt.Sprintf("\t\t%s: optSlice(cmd.Flags().Changed(%q), o.%s),\n", opt.FieldName, opt.Name, opt.FieldName))
			buf.WriteString(fmt.Sprintf("\t\tCderun%s: optSlice(cmd.Flags().Changed(%q), o.Cderun%s),\n", opt.FieldName, "cderun-"+opt.Name, opt.FieldName))
		} else {
			buf.WriteString(fmt.Sprintf("\t\t%s: opt(cmd.Flags().Changed(%q), o.%s),\n", opt.FieldName, opt.Name, opt.FieldName))
			buf.WriteString(fmt.Sprintf("\t\tCderun%s: opt(cmd.Flags().Changed(%q), o.Cderun%s),\n", opt.FieldName, "cderun-"+opt.Name, opt.FieldName))
		}
	}
	buf.WriteString("\t}\n")
	buf.WriteString("}\n\n")

	buf.WriteString("func opt[T any](changed bool, v T) *T {\n")
	buf.WriteString("\tif !changed { return nil }\n")
	buf.WriteString("\treturn &v\n")
	buf.WriteString("}\n\n")

	buf.WriteString("func optSlice[T any](changed bool, v []T) []T {\n")
	buf.WriteString("\tif !changed { return nil }\n")
	buf.WriteString("\treturn v\n")
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}

	return os.WriteFile(outPath, formatted, 0644)
}

func PascalCase(s string) string {
	initialisms := map[string]string{
		"tty":  "TTY",
		"dns":  "DNS",
		"cpus": "CPUs",
	}
	var builder strings.Builder
	parts := strings.Split(s, "-")
	for _, part := range parts {
		if part == "" {
			continue
		}
		if val, ok := initialisms[strings.ToLower(part)]; ok {
			builder.WriteString(val)
			continue
		}
		builder.WriteString(strings.ToUpper(part[0:1]))
		builder.WriteString(part[1:])
	}
	return builder.String()
}
