// Code generated by genflags.go. DO NOT EDIT.
package command

import (
	"cderun/internal/config"
	"github.com/spf13/cobra"
)

// flagOptions contains plain types for Cobra binding.
type flagOptions struct {
	AddHosts              []string
	CderunAddHosts        []string
	CPUs                  float64
	CderunCPUs            float64
	CapAdd                []string
	CderunCapAdd          []string
	CapDrop               []string
	CderunCapDrop         []string
	Config                string
	CderunConfig          string
	DNS                   []string
	CderunDNS             []string
	Devices               []string
	CderunDevices         []string
	Diagnosis             bool
	CderunDiagnosis       bool
	DiagnosisFormat       string
	CderunDiagnosisFormat string
	DryRun                bool
	CderunDryRun          bool
	DryRunFormat          string
	CderunDryRunFormat    string
	Entrypoint            []string
	CderunEntrypoint      []string
	Env                   []string
	CderunEnv             []string
	Expose                []string
	CderunExpose          []string
	HangTimeout           string
	CderunHangTimeout     string
	Hostname              string
	CderunHostname        string
	Image                 string
	CderunImage           string
	Interactive           bool
	CderunInteractive     bool
	LogFormat             string
	CderunLogFormat       string
	LogLevel              string
	CderunLogLevel        string
	LogTimestamp          bool
	CderunLogTimestamp    bool
	Memory                string
	CderunMemory          string
	MountAllTools         bool
	CderunMountAllTools   bool
	MountCderun           bool
	CderunMountCderun     bool
	MountCderunPath       string
	CderunMountCderunPath string
	MountSocket           bool
	CderunMountSocket     bool
	MountSocketPath       string
	CderunMountSocketPath string
	MountTools            string
	CderunMountTools      string
	Mounts                []string
	CderunMounts          []string
	Network               string
	CderunNetwork         string
	Ports                 []string
	CderunPorts           []string
	Privileged            bool
	CderunPrivileged      bool
	PublishAll            bool
	CderunPublishAll      bool
	Pull                  string
	CderunPull            string
	PullBackoffBase       string
	CderunPullBackoffBase string
	PullMaxRetries        int
	CderunPullMaxRetries  int
	Remove                bool
	CderunRemove          bool
	Runtime               string
	CderunRuntime         string
	SensitiveEnv          []string
	CderunSensitiveEnv    []string
	SocketPath            string
	CderunSocketPath      string
	StrictEnv             bool
	CderunStrictEnv       bool
	TTY                   bool
	CderunTTY             bool
	ToolConfig            string
	CderunToolConfig      string
	User                  string
	CderunUser            string
	Workdir               string
	CderunWorkdir         string
}

func (o *rootOptions) registerFlags(cmd *cobra.Command) {
	f := cmd.PersistentFlags()
	f.StringArrayVar(&o.AddHosts, "add-host", nil, "Add a custom host-to-IP mapping (host:ip)")
	f.StringArrayVar(&o.CderunAddHosts, "cderun-add-host", nil, "Override add-host setting (highest priority, can be used after subcommand)")
	f.Float64Var(&o.CPUs, "cpus", 0, "Number of CPUs")
	f.Float64Var(&o.CderunCPUs, "cderun-cpus", 0, "Override cpus setting (highest priority, can be used after subcommand)")
	f.StringArrayVar(&o.CapAdd, "cap-add", nil, "Add Linux capabilities")
	f.StringArrayVar(&o.CderunCapAdd, "cderun-cap-add", nil, "Override cap-add setting (highest priority, can be used after subcommand)")
	f.StringArrayVar(&o.CapDrop, "cap-drop", nil, "Drop Linux capabilities")
	f.StringArrayVar(&o.CderunCapDrop, "cderun-cap-drop", nil, "Override cap-drop setting (highest priority, can be used after subcommand)")
	f.StringVar(&o.Config, "config", "", "Path to cderun config file")
	f.StringVar(&o.CderunConfig, "cderun-config", "", "Override config setting (highest priority, can be used after subcommand)")
	f.StringArrayVar(&o.DNS, "dns", nil, "Set custom DNS servers")
	f.StringArrayVar(&o.CderunDNS, "cderun-dns", nil, "Override dns setting (highest priority, can be used after subcommand)")
	f.StringArrayVar(&o.Devices, "device", nil, "Add a host device to the container")
	f.StringArrayVar(&o.CderunDevices, "cderun-device", nil, "Override device setting (highest priority, can be used after subcommand)")
	f.BoolVar(&o.Diagnosis, "diagnosis", false, "Show system diagnostics and available tools")
	f.BoolVar(&o.CderunDiagnosis, "cderun-diagnosis", false, "Override diagnosis setting (highest priority, can be used after subcommand)")
	f.StringVar(&o.DiagnosisFormat, "diagnosis-format", "yaml", "Diagnosis output format (yaml, json, simple)")
	f.StringVar(&o.CderunDiagnosisFormat, "cderun-diagnosis-format", "", "Override diagnosis-format setting (highest priority, can be used after subcommand)")
	f.BoolVar(&o.DryRun, "dry-run", false, "Preview container configuration without execution")
	f.BoolVar(&o.CderunDryRun, "cderun-dry-run", false, "Override dry-run setting (highest priority, can be used after subcommand)")
	f.StringVarP(&o.DryRunFormat, "dry-run-format", "f", "yaml", "Output format (yaml, json, simple)")
	f.StringVar(&o.CderunDryRunFormat, "cderun-dry-run-format", "", "Override dry-run-format setting (highest priority, can be used after subcommand)")
	f.StringArrayVar(&o.Entrypoint, "entrypoint", nil, "Overwrite the default ENTRYPOINT of the image")
	f.StringArrayVar(&o.CderunEntrypoint, "cderun-entrypoint", nil, "Override entrypoint setting (highest priority, can be used after subcommand)")
	f.StringArrayVarP(&o.Env, "env", "e", nil, "Set environment variables")
	f.StringArrayVar(&o.CderunEnv, "cderun-env", nil, "Override env setting (highest priority, can be used after subcommand)")
	f.StringArrayVar(&o.Expose, "expose", nil, "Expose a port or a range of ports")
	f.StringArrayVar(&o.CderunExpose, "cderun-expose", nil, "Override expose setting (highest priority, can be used after subcommand)")
	f.StringVar(&o.HangTimeout, "hang-timeout", "10s", "Grace period after I/O completion before force-terminating the container (e.g. 10s, 5s)")
	f.StringVar(&o.CderunHangTimeout, "cderun-hang-timeout", "", "Override hang-timeout setting (highest priority, can be used after subcommand)")
	f.StringVar(&o.Hostname, "hostname", "", "Container host name")
	f.StringVar(&o.CderunHostname, "cderun-hostname", "", "Override hostname setting (highest priority, can be used after subcommand)")
	f.StringVar(&o.Image, "image", "", "Docker image to use")
	f.StringVar(&o.CderunImage, "cderun-image", "", "Override image setting (highest priority, can be used after subcommand)")
	f.BoolVarP(&o.Interactive, "interactive", "i", false, "Keep STDIN open even if not attached")
	f.BoolVar(&o.CderunInteractive, "cderun-interactive", false, "Override interactive setting (highest priority, can be used after subcommand)")
	f.StringVar(&o.LogFormat, "log-format", "text", "Set log format (text, json)")
	f.StringVar(&o.CderunLogFormat, "cderun-log-format", "", "Override log-format setting (highest priority, can be used after subcommand)")
	f.StringVar(&o.LogLevel, "log-level", "warn", "Set log level (error, warn, info, debug, trace)")
	f.StringVar(&o.CderunLogLevel, "cderun-log-level", "", "Override log-level setting (highest priority, can be used after subcommand)")
	f.BoolVar(&o.LogTimestamp, "log-timestamp", true, "Include timestamp in logs")
	f.BoolVar(&o.CderunLogTimestamp, "cderun-log-timestamp", true, "Override log-timestamp setting (highest priority, can be used after subcommand)")
	f.StringVarP(&o.Memory, "memory", "m", "", "Memory limit")
	f.StringVar(&o.CderunMemory, "cderun-memory", "", "Override memory setting (highest priority, can be used after subcommand)")
	f.BoolVar(&o.MountAllTools, "mount-all-tools", false, "Mount all defined tools into the container")
	f.BoolVar(&o.CderunMountAllTools, "cderun-mount-all-tools", false, "Override mount-all-tools setting (highest priority, can be used after subcommand)")
	f.BoolVar(&o.MountCderun, "mount-cderun", false, "Mount cderun binary for use inside container")
	f.BoolVar(&o.CderunMountCderun, "cderun-mount-cderun", false, "Override mount-cderun setting (highest priority, can be used after subcommand)")
	f.StringVar(&o.MountCderunPath, "mount-cderun-path", "", "Host path to cderun binary to mount inside container")
	f.StringVar(&o.CderunMountCderunPath, "cderun-mount-cderun-path", "", "Override mount-cderun-path setting (highest priority, can be used after subcommand)")
	f.BoolVar(&o.MountSocket, "mount-socket", false, "Mount the container runtime socket into the container")
	f.BoolVar(&o.CderunMountSocket, "cderun-mount-socket", false, "Override mount-socket setting (highest priority, can be used after subcommand)")
	f.StringVar(&o.MountSocketPath, "mount-socket-path", "", "Path where the socket should be mounted inside the container (defaults to host path)")
	f.StringVar(&o.CderunMountSocketPath, "cderun-mount-socket-path", "", "Override mount-socket-path setting (highest priority, can be used after subcommand)")
	f.StringVar(&o.MountTools, "mount-tools", "", "Mount specified tools into the container")
	f.StringVar(&o.CderunMountTools, "cderun-mount-tools", "", "Override mount-tools setting (highest priority, can be used after subcommand)")
	f.StringArrayVar(&o.Mounts, "mount", nil, "Attach a filesystem mount to the container")
	f.StringArrayVar(&o.CderunMounts, "cderun-mount", nil, "Override mount setting (highest priority, can be used after subcommand)")
	f.StringVar(&o.Network, "network", "bridge", "Connect a container to a network")
	f.StringVar(&o.CderunNetwork, "cderun-network", "", "Override network setting (highest priority, can be used after subcommand)")
	f.StringArrayVarP(&o.Ports, "publish", "p", nil, "Publish a container's port(s) to the host")
	f.StringArrayVar(&o.CderunPorts, "cderun-publish", nil, "Override publish setting (highest priority, can be used after subcommand)")
	f.BoolVar(&o.Privileged, "privileged", false, "Give extended privileges to this container")
	f.BoolVar(&o.CderunPrivileged, "cderun-privileged", false, "Override privileged setting (highest priority, can be used after subcommand)")
	f.BoolVarP(&o.PublishAll, "publish-all", "P", false, "Publish all exposed ports to random ports")
	f.BoolVar(&o.CderunPublishAll, "cderun-publish-all", false, "Override publish-all setting (highest priority, can be used after subcommand)")
	f.StringVar(&o.Pull, "pull", "missing", "Pull image before running (always, missing, never)")
	f.StringVar(&o.CderunPull, "cderun-pull", "", "Override pull setting (highest priority, can be used after subcommand)")
	f.StringVar(&o.PullBackoffBase, "pull-backoff-base", "1s", "Base duration for exponential backoff during image pull (e.g. 1s, 500ms)")
	f.StringVar(&o.CderunPullBackoffBase, "cderun-pull-backoff-base", "", "Override pull-backoff-base setting (highest priority, can be used after subcommand)")
	f.IntVar(&o.PullMaxRetries, "pull-max-retries", 3, "Maximum number of retries for image pull")
	f.IntVar(&o.CderunPullMaxRetries, "cderun-pull-max-retries", 0, "Override pull-max-retries setting (highest priority, can be used after subcommand)")
	f.BoolVar(&o.Remove, "remove", true, "Automatically remove the container when it exits")
	f.BoolVar(&o.CderunRemove, "cderun-remove", true, "Override remove setting (highest priority, can be used after subcommand)")
	f.StringVar(&o.Runtime, "runtime", "", "Container runtime to use (docker/podman)")
	f.StringVar(&o.CderunRuntime, "cderun-runtime", "", "Override runtime setting (highest priority, can be used after subcommand)")
	f.StringArrayVar(&o.SensitiveEnv, "sensitive-env", nil, "List of environment variable patterns to mask (default uses automatic keywords)")
	f.StringArrayVar(&o.CderunSensitiveEnv, "cderun-sensitive-env", nil, "Override sensitive-env setting (highest priority, can be used after subcommand)")
	f.StringVar(&o.SocketPath, "socket-path", "", "Path to the container runtime socket on the host")
	f.StringVar(&o.CderunSocketPath, "cderun-socket-path", "", "Override socket-path setting (highest priority, can be used after subcommand)")
	f.BoolVar(&o.StrictEnv, "strict-env", false, "Require all environment variables to be present on the host")
	f.BoolVar(&o.CderunStrictEnv, "cderun-strict-env", false, "Override strict-env setting (highest priority, can be used after subcommand)")
	f.BoolVarP(&o.TTY, "tty", "t", false, "Allocate a pseudo-TTY")
	f.BoolVar(&o.CderunTTY, "cderun-tty", false, "Override tty setting (highest priority, can be used after subcommand)")
	f.StringVar(&o.ToolConfig, "tool-config", "", "Path to tools config file")
	f.StringVar(&o.CderunToolConfig, "cderun-tool-config", "", "Override tool-config setting (highest priority, can be used after subcommand)")
	f.StringVarP(&o.User, "user", "u", "", "Username or UID (format: <name|uid>[:<group|gid>])")
	f.StringVar(&o.CderunUser, "cderun-user", "", "Override user setting (highest priority, can be used after subcommand)")
	f.StringVarP(&o.Workdir, "workdir", "w", "", "Working directory inside the container")
	f.StringVar(&o.CderunWorkdir, "cderun-workdir", "", "Override workdir setting (highest priority, can be used after subcommand)")
}

func (o *rootOptions) buildCLIOptions(cmd *cobra.Command) config.CLIOptions {
	return config.CLIOptions{
		AddHosts:              optSlice(cmd.Flags().Changed("add-host"), o.AddHosts),
		CderunAddHosts:        optSlice(cmd.Flags().Changed("cderun-add-host"), o.CderunAddHosts),
		CPUs:                  opt(cmd.Flags().Changed("cpus"), o.CPUs),
		CderunCPUs:            opt(cmd.Flags().Changed("cderun-cpus"), o.CderunCPUs),
		CapAdd:                optSlice(cmd.Flags().Changed("cap-add"), o.CapAdd),
		CderunCapAdd:          optSlice(cmd.Flags().Changed("cderun-cap-add"), o.CderunCapAdd),
		CapDrop:               optSlice(cmd.Flags().Changed("cap-drop"), o.CapDrop),
		CderunCapDrop:         optSlice(cmd.Flags().Changed("cderun-cap-drop"), o.CderunCapDrop),
		Config:                opt(cmd.Flags().Changed("config"), o.Config),
		CderunConfig:          opt(cmd.Flags().Changed("cderun-config"), o.CderunConfig),
		DNS:                   optSlice(cmd.Flags().Changed("dns"), o.DNS),
		CderunDNS:             optSlice(cmd.Flags().Changed("cderun-dns"), o.CderunDNS),
		Devices:               optSlice(cmd.Flags().Changed("device"), o.Devices),
		CderunDevices:         optSlice(cmd.Flags().Changed("cderun-device"), o.CderunDevices),
		Diagnosis:             opt(cmd.Flags().Changed("diagnosis"), o.Diagnosis),
		CderunDiagnosis:       opt(cmd.Flags().Changed("cderun-diagnosis"), o.CderunDiagnosis),
		DiagnosisFormat:       opt(cmd.Flags().Changed("diagnosis-format"), o.DiagnosisFormat),
		CderunDiagnosisFormat: opt(cmd.Flags().Changed("cderun-diagnosis-format"), o.CderunDiagnosisFormat),
		DryRun:                opt(cmd.Flags().Changed("dry-run"), o.DryRun),
		CderunDryRun:          opt(cmd.Flags().Changed("cderun-dry-run"), o.CderunDryRun),
		DryRunFormat:          opt(cmd.Flags().Changed("dry-run-format"), o.DryRunFormat),
		CderunDryRunFormat:    opt(cmd.Flags().Changed("cderun-dry-run-format"), o.CderunDryRunFormat),
		Entrypoint:            optSlice(cmd.Flags().Changed("entrypoint"), o.Entrypoint),
		CderunEntrypoint:      optSlice(cmd.Flags().Changed("cderun-entrypoint"), o.CderunEntrypoint),
		Env:                   optSlice(cmd.Flags().Changed("env"), o.Env),
		CderunEnv:             optSlice(cmd.Flags().Changed("cderun-env"), o.CderunEnv),
		Expose:                optSlice(cmd.Flags().Changed("expose"), o.Expose),
		CderunExpose:          optSlice(cmd.Flags().Changed("cderun-expose"), o.CderunExpose),
		HangTimeout:           opt(cmd.Flags().Changed("hang-timeout"), o.HangTimeout),
		CderunHangTimeout:     opt(cmd.Flags().Changed("cderun-hang-timeout"), o.CderunHangTimeout),
		Hostname:              opt(cmd.Flags().Changed("hostname"), o.Hostname),
		CderunHostname:        opt(cmd.Flags().Changed("cderun-hostname"), o.CderunHostname),
		Image:                 opt(cmd.Flags().Changed("image"), o.Image),
		CderunImage:           opt(cmd.Flags().Changed("cderun-image"), o.CderunImage),
		Interactive:           opt(cmd.Flags().Changed("interactive"), o.Interactive),
		CderunInteractive:     opt(cmd.Flags().Changed("cderun-interactive"), o.CderunInteractive),
		LogFormat:             opt(cmd.Flags().Changed("log-format"), o.LogFormat),
		CderunLogFormat:       opt(cmd.Flags().Changed("cderun-log-format"), o.CderunLogFormat),
		LogLevel:              opt(cmd.Flags().Changed("log-level"), o.LogLevel),
		CderunLogLevel:        opt(cmd.Flags().Changed("cderun-log-level"), o.CderunLogLevel),
		LogTimestamp:          opt(cmd.Flags().Changed("log-timestamp"), o.LogTimestamp),
		CderunLogTimestamp:    opt(cmd.Flags().Changed("cderun-log-timestamp"), o.CderunLogTimestamp),
		Memory:                opt(cmd.Flags().Changed("memory"), o.Memory),
		CderunMemory:          opt(cmd.Flags().Changed("cderun-memory"), o.CderunMemory),
		MountAllTools:         opt(cmd.Flags().Changed("mount-all-tools"), o.MountAllTools),
		CderunMountAllTools:   opt(cmd.Flags().Changed("cderun-mount-all-tools"), o.CderunMountAllTools),
		MountCderun:           opt(cmd.Flags().Changed("mount-cderun"), o.MountCderun),
		CderunMountCderun:     opt(cmd.Flags().Changed("cderun-mount-cderun"), o.CderunMountCderun),
		MountCderunPath:       opt(cmd.Flags().Changed("mount-cderun-path"), o.MountCderunPath),
		CderunMountCderunPath: opt(cmd.Flags().Changed("cderun-mount-cderun-path"), o.CderunMountCderunPath),
		MountSocket:           opt(cmd.Flags().Changed("mount-socket"), o.MountSocket),
		CderunMountSocket:     opt(cmd.Flags().Changed("cderun-mount-socket"), o.CderunMountSocket),
		MountSocketPath:       opt(cmd.Flags().Changed("mount-socket-path"), o.MountSocketPath),
		CderunMountSocketPath: opt(cmd.Flags().Changed("cderun-mount-socket-path"), o.CderunMountSocketPath),
		MountTools:            opt(cmd.Flags().Changed("mount-tools"), o.MountTools),
		CderunMountTools:      opt(cmd.Flags().Changed("cderun-mount-tools"), o.CderunMountTools),
		Mounts:                optSlice(cmd.Flags().Changed("mount"), o.Mounts),
		CderunMounts:          optSlice(cmd.Flags().Changed("cderun-mount"), o.CderunMounts),
		Network:               opt(cmd.Flags().Changed("network"), o.Network),
		CderunNetwork:         opt(cmd.Flags().Changed("cderun-network"), o.CderunNetwork),
		Ports:                 optSlice(cmd.Flags().Changed("publish"), o.Ports),
		CderunPorts:           optSlice(cmd.Flags().Changed("cderun-publish"), o.CderunPorts),
		Privileged:            opt(cmd.Flags().Changed("privileged"), o.Privileged),
		CderunPrivileged:      opt(cmd.Flags().Changed("cderun-privileged"), o.CderunPrivileged),
		PublishAll:            opt(cmd.Flags().Changed("publish-all"), o.PublishAll),
		CderunPublishAll:      opt(cmd.Flags().Changed("cderun-publish-all"), o.CderunPublishAll),
		Pull:                  opt(cmd.Flags().Changed("pull"), o.Pull),
		CderunPull:            opt(cmd.Flags().Changed("cderun-pull"), o.CderunPull),
		PullBackoffBase:       opt(cmd.Flags().Changed("pull-backoff-base"), o.PullBackoffBase),
		CderunPullBackoffBase: opt(cmd.Flags().Changed("cderun-pull-backoff-base"), o.CderunPullBackoffBase),
		PullMaxRetries:        opt(cmd.Flags().Changed("pull-max-retries"), o.PullMaxRetries),
		CderunPullMaxRetries:  opt(cmd.Flags().Changed("cderun-pull-max-retries"), o.CderunPullMaxRetries),
		Remove:                opt(cmd.Flags().Changed("remove"), o.Remove),
		CderunRemove:          opt(cmd.Flags().Changed("cderun-remove"), o.CderunRemove),
		Runtime:               opt(cmd.Flags().Changed("runtime"), o.Runtime),
		CderunRuntime:         opt(cmd.Flags().Changed("cderun-runtime"), o.CderunRuntime),
		SensitiveEnv:          optSlice(cmd.Flags().Changed("sensitive-env"), o.SensitiveEnv),
		CderunSensitiveEnv:    optSlice(cmd.Flags().Changed("cderun-sensitive-env"), o.CderunSensitiveEnv),
		SocketPath:            opt(cmd.Flags().Changed("socket-path"), o.SocketPath),
		CderunSocketPath:      opt(cmd.Flags().Changed("cderun-socket-path"), o.CderunSocketPath),
		StrictEnv:             opt(cmd.Flags().Changed("strict-env"), o.StrictEnv),
		CderunStrictEnv:       opt(cmd.Flags().Changed("cderun-strict-env"), o.CderunStrictEnv),
		TTY:                   opt(cmd.Flags().Changed("tty"), o.TTY),
		CderunTTY:             opt(cmd.Flags().Changed("cderun-tty"), o.CderunTTY),
		ToolConfig:            opt(cmd.Flags().Changed("tool-config"), o.ToolConfig),
		CderunToolConfig:      opt(cmd.Flags().Changed("cderun-tool-config"), o.CderunToolConfig),
		User:                  opt(cmd.Flags().Changed("user"), o.User),
		CderunUser:            opt(cmd.Flags().Changed("cderun-user"), o.CderunUser),
		Workdir:               opt(cmd.Flags().Changed("workdir"), o.Workdir),
		CderunWorkdir:         opt(cmd.Flags().Changed("cderun-workdir"), o.CderunWorkdir),
	}
}

func opt[T any](changed bool, v T) *T {
	if !changed {
		return nil
	}
	return &v
}

func optSlice[T any](changed bool, v []T) []T {
	if !changed {
		return nil
	}
	return v
}
