// Code generated by scripts/gen-options.go. DO NOT EDIT.

package command

import (
	"cderun/internal/config"
	"github.com/spf13/cobra"
)

type rootOptionsGen struct {
	network               string
	cderunNetwork         string
	socketPath            string
	cderunSocketPath      string
	mountSocketPath       string
	cderunMountSocketPath string
	mountCderunPath       string
	cderunMountCderunPath string
	image                 string
	cderunImage           string
	runtime               string
	cderunRuntime         string
	workdir               string
	cderunWorkdir         string
	mountTools            string
	cderunMountTools      string
	config                string
	cderunConfig          string
	toolConfig            string
	cderunToolConfig      string
	hostname              string
	cderunHostname        string
	user                  string
	cderunUser            string
	pull                  string
	cderunPull            string
	pullBackoffBase       string
	cderunPullBackoffBase string
	memory                string
	cderunMemory          string
	dryRunFormat          string
	cderunDryRunFormat    string
	diagnosisFormat       string
	cderunDiagnosisFormat string
	logLevel              string
	cderunLogLevel        string
	logFormat             string
	cderunLogFormat       string
	hangTimeout           string
	cderunHangTimeout     string
	tTY                   bool
	cderunTTY             bool
	interactive           bool
	cderunInteractive     bool
	mountSocket           bool
	cderunMountSocket     bool
	mountCderun           bool
	cderunMountCderun     bool
	mountAllTools         bool
	cderunMountAllTools   bool
	remove                bool
	cderunRemove          bool
	publishAll            bool
	cderunPublishAll      bool
	privileged            bool
	cderunPrivileged      bool
	strictEnv             bool
	cderunStrictEnv       bool
	dryRun                bool
	cderunDryRun          bool
	diagnosis             bool
	cderunDiagnosis       bool
	logTimestamp          bool
	cderunLogTimestamp    bool
	pullMaxRetries        int
	cderunPullMaxRetries  int
	cPUs                  float64
	cderunCPUs            float64
	env                   []string
	cderunEnv             []string
	mounts                []string
	cderunMounts          []string
	ports                 []string
	cderunPorts           []string
	expose                []string
	cderunExpose          []string
	dNS                   []string
	cderunDNS             []string
	addHosts              []string
	cderunAddHosts        []string
	capAdd                []string
	cderunCapAdd          []string
	capDrop               []string
	cderunCapDrop         []string
	entrypoint            []string
	cderunEntrypoint      []string
	devices               []string
	cderunDevices         []string
}

func (o *rootOptions) populateCLIOptions(cmd *cobra.Command) config.CLIOptions {
	return config.CLIOptions{
		Network:               opt(cmd.Flags().Changed("network"), o.network),
		CderunNetwork:         opt(cmd.Flags().Changed("cderun-network"), o.cderunNetwork),
		SocketPath:            opt(cmd.Flags().Changed("socket-path"), o.socketPath),
		CderunSocketPath:      opt(cmd.Flags().Changed("cderun-socket-path"), o.cderunSocketPath),
		MountSocketPath:       opt(cmd.Flags().Changed("mount-socket-path"), o.mountSocketPath),
		CderunMountSocketPath: opt(cmd.Flags().Changed("cderun-mount-socket-path"), o.cderunMountSocketPath),
		MountCderunPath:       opt(cmd.Flags().Changed("mount-cderun-path"), o.mountCderunPath),
		CderunMountCderunPath: opt(cmd.Flags().Changed("cderun-mount-cderun-path"), o.cderunMountCderunPath),
		Image:                 opt(cmd.Flags().Changed("image"), o.image),
		CderunImage:           opt(cmd.Flags().Changed("cderun-image"), o.cderunImage),
		Runtime:               opt(cmd.Flags().Changed("runtime"), o.runtime),
		CderunRuntime:         opt(cmd.Flags().Changed("cderun-runtime"), o.cderunRuntime),
		Workdir:               opt(cmd.Flags().Changed("workdir"), o.workdir),
		CderunWorkdir:         opt(cmd.Flags().Changed("cderun-workdir"), o.cderunWorkdir),
		MountTools:            opt(cmd.Flags().Changed("mount-tools"), o.mountTools),
		CderunMountTools:      opt(cmd.Flags().Changed("cderun-mount-tools"), o.cderunMountTools),
		Config:                opt(cmd.Flags().Changed("config"), o.config),
		CderunConfig:          opt(cmd.Flags().Changed("cderun-config"), o.cderunConfig),
		ToolConfig:            opt(cmd.Flags().Changed("tool-config"), o.toolConfig),
		CderunToolConfig:      opt(cmd.Flags().Changed("cderun-tool-config"), o.cderunToolConfig),
		Hostname:              opt(cmd.Flags().Changed("hostname"), o.hostname),
		CderunHostname:        opt(cmd.Flags().Changed("cderun-hostname"), o.cderunHostname),
		User:                  opt(cmd.Flags().Changed("user"), o.user),
		CderunUser:            opt(cmd.Flags().Changed("cderun-user"), o.cderunUser),
		Pull:                  opt(cmd.Flags().Changed("pull"), o.pull),
		CderunPull:            opt(cmd.Flags().Changed("cderun-pull"), o.cderunPull),
		PullBackoffBase:       opt(cmd.Flags().Changed("pull-backoff-base"), o.pullBackoffBase),
		CderunPullBackoffBase: opt(cmd.Flags().Changed("cderun-pull-backoff-base"), o.cderunPullBackoffBase),
		Memory:                opt(cmd.Flags().Changed("memory"), o.memory),
		CderunMemory:          opt(cmd.Flags().Changed("cderun-memory"), o.cderunMemory),
		DryRunFormat:          opt(cmd.Flags().Changed("dry-run-format"), o.dryRunFormat),
		CderunDryRunFormat:    opt(cmd.Flags().Changed("cderun-dry-run-format"), o.cderunDryRunFormat),
		DiagnosisFormat:       opt(cmd.Flags().Changed("diagnosis-format"), o.diagnosisFormat),
		CderunDiagnosisFormat: opt(cmd.Flags().Changed("cderun-diagnosis-format"), o.cderunDiagnosisFormat),
		LogLevel:              opt(cmd.Flags().Changed("log-level"), o.logLevel),
		CderunLogLevel:        opt(cmd.Flags().Changed("cderun-log-level"), o.cderunLogLevel),
		LogFormat:             opt(cmd.Flags().Changed("log-format"), o.logFormat),
		CderunLogFormat:       opt(cmd.Flags().Changed("cderun-log-format"), o.cderunLogFormat),
		HangTimeout:           opt(cmd.Flags().Changed("hang-timeout"), o.hangTimeout),
		CderunHangTimeout:     opt(cmd.Flags().Changed("cderun-hang-timeout"), o.cderunHangTimeout),
		TTY:                   opt(cmd.Flags().Changed("tty"), o.tTY),
		CderunTTY:             opt(cmd.Flags().Changed("cderun-tty"), o.cderunTTY),
		Interactive:           opt(cmd.Flags().Changed("interactive"), o.interactive),
		CderunInteractive:     opt(cmd.Flags().Changed("cderun-interactive"), o.cderunInteractive),
		MountSocket:           opt(cmd.Flags().Changed("mount-socket"), o.mountSocket),
		CderunMountSocket:     opt(cmd.Flags().Changed("cderun-mount-socket"), o.cderunMountSocket),
		MountCderun:           opt(cmd.Flags().Changed("mount-cderun"), o.mountCderun),
		CderunMountCderun:     opt(cmd.Flags().Changed("cderun-mount-cderun"), o.cderunMountCderun),
		MountAllTools:         opt(cmd.Flags().Changed("mount-all-tools"), o.mountAllTools),
		CderunMountAllTools:   opt(cmd.Flags().Changed("cderun-mount-all-tools"), o.cderunMountAllTools),
		Remove:                opt(cmd.Flags().Changed("remove"), o.remove),
		CderunRemove:          opt(cmd.Flags().Changed("cderun-remove"), o.cderunRemove),
		PublishAll:            opt(cmd.Flags().Changed("publish-all"), o.publishAll),
		CderunPublishAll:      opt(cmd.Flags().Changed("cderun-publish-all"), o.cderunPublishAll),
		Privileged:            opt(cmd.Flags().Changed("privileged"), o.privileged),
		CderunPrivileged:      opt(cmd.Flags().Changed("cderun-privileged"), o.cderunPrivileged),
		StrictEnv:             opt(cmd.Flags().Changed("strict-env"), o.strictEnv),
		CderunStrictEnv:       opt(cmd.Flags().Changed("cderun-strict-env"), o.cderunStrictEnv),
		DryRun:                opt(cmd.Flags().Changed("dry-run"), o.dryRun),
		CderunDryRun:          opt(cmd.Flags().Changed("cderun-dry-run"), o.cderunDryRun),
		Diagnosis:             opt(cmd.Flags().Changed("diagnosis"), o.diagnosis),
		CderunDiagnosis:       opt(cmd.Flags().Changed("cderun-diagnosis"), o.cderunDiagnosis),
		LogTimestamp:          opt(cmd.Flags().Changed("log-timestamp"), o.logTimestamp),
		CderunLogTimestamp:    opt(cmd.Flags().Changed("cderun-log-timestamp"), o.cderunLogTimestamp),
		PullMaxRetries:        opt(cmd.Flags().Changed("pull-max-retries"), o.pullMaxRetries),
		CderunPullMaxRetries:  opt(cmd.Flags().Changed("cderun-pull-max-retries"), o.cderunPullMaxRetries),
		CPUs:                  opt(cmd.Flags().Changed("cpus"), o.cPUs),
		CderunCPUs:            opt(cmd.Flags().Changed("cderun-cpus"), o.cderunCPUs),
		Env:                   o.env,
		CderunEnv:             o.cderunEnv,
		Mounts:                o.mounts,
		CderunMounts:          o.cderunMounts,
		Ports:                 o.ports,
		CderunPorts:           o.cderunPorts,
		Expose:                o.expose,
		CderunExpose:          o.cderunExpose,
		DNS:                   o.dNS,
		CderunDNS:             o.cderunDNS,
		AddHosts:              o.addHosts,
		CderunAddHosts:        o.cderunAddHosts,
		CapAdd:                o.capAdd,
		CderunCapAdd:          o.cderunCapAdd,
		CapDrop:               o.capDrop,
		CderunCapDrop:         o.cderunCapDrop,
		Entrypoint:            o.entrypoint,
		CderunEntrypoint:      o.cderunEntrypoint,
		Devices:               o.devices,
		CderunDevices:         o.cderunDevices,
	}
}
