// Code generated by scripts/gen_options.go; DO NOT EDIT.

package command

import (
	"cderun/internal/config"
	"github.com/spf13/cobra"
)

// rootFlags contains fields bound to cobra flag definitions.
type rootFlags struct {
	addHosts              []string
	cderunAddHosts        []string
	capAdd                []string
	cderunCapAdd          []string
	capDrop               []string
	cderunCapDrop         []string
	config                string
	cderunConfig          string
	cpus                  float64
	cderunCPUs            float64
	devices               []string
	cderunDevices         []string
	diagnosis             bool
	cderunDiagnosis       bool
	diagnosisFormat       string
	cderunDiagnosisFormat string
	dns                   []string
	cderunDNS             []string
	dryRun                bool
	cderunDryRun          bool
	dryRunFormat          string
	cderunDryRunFormat    string
	entrypoint            []string
	cderunEntrypoint      []string
	env                   []string
	cderunEnv             []string
	expose                []string
	cderunExpose          []string
	groupAdd              []string
	cderunGroupAdd        []string
	hangTimeout           string
	cderunHangTimeout     string
	hostname              string
	cderunHostname        string
	image                 string
	cderunImage           string
	init                  bool
	cderunInit            bool
	interactive           bool
	cderunInteractive     bool
	ipc                   string
	cderunIpc             string
	logFormat             string
	cderunLogFormat       string
	logLevel              string
	cderunLogLevel        string
	logTimestamp          bool
	cderunLogTimestamp    bool
	memory                string
	cderunMemory          string
	mounts                []string
	cderunMounts          []string
	mountAllTools         bool
	cderunMountAllTools   bool
	mountCderun           bool
	cderunMountCderun     bool
	mountCderunPath       string
	cderunMountCderunPath string
	mountSocket           bool
	cderunMountSocket     bool
	mountSocketPath       string
	cderunMountSocketPath string
	mountTools            string
	cderunMountTools      string
	network               string
	cderunNetwork         string
	pid                   string
	cderunPid             string
	privileged            bool
	cderunPrivileged      bool
	ports                 []string
	cderunPorts           []string
	publishAll            bool
	cderunPublishAll      bool
	pull                  string
	cderunPull            string
	pullBackoffBase       string
	cderunPullBackoffBase string
	pullMaxRetries        int
	cderunPullMaxRetries  int
	readOnly              bool
	cderunReadOnly        bool
	remove                bool
	cderunRemove          bool
	runtime               string
	cderunRuntime         string
	sensitiveEnv          []string
	cderunSensitiveEnv    []string
	socketPath            string
	cderunSocketPath      string
	strictEnv             bool
	cderunStrictEnv       bool
	sysctls               []string
	cderunSysctls         []string
	toolConfig            string
	cderunToolConfig      string
	tty                   bool
	cderunTTY             bool
	ulimits               []string
	cderunUlimits         []string
	user                  string
	cderunUser            string
	workdir               string
	cderunWorkdir         string
}

// buildCLIOptions dynamically builds and populates config.CLIOptions from command flags.
func buildCLIOptions(cmd *cobra.Command, o *rootOptions) config.CLIOptions {
	optBool := func(changed bool, v bool) *bool {
		if !changed {
			return nil
		}
		return &v
	}
	optStr := func(changed bool, v string) *string {
		if !changed {
			return nil
		}
		return &v
	}
	optInt := func(changed bool, v int) *int {
		if !changed {
			return nil
		}
		return &v
	}
	optFloat := func(changed bool, v float64) *float64 {
		if !changed {
			return nil
		}
		return &v
	}

	return config.CLIOptions{
		AddHosts:              o.addHosts,
		CderunAddHosts:        o.cderunAddHosts,
		CapAdd:                o.capAdd,
		CderunCapAdd:          o.cderunCapAdd,
		CapDrop:               o.capDrop,
		CderunCapDrop:         o.cderunCapDrop,
		Config:                optStr(cmd.Flags().Changed("config"), o.config),
		CderunConfig:          optStr(cmd.Flags().Changed("cderun-config"), o.cderunConfig),
		CPUs:                  optFloat(cmd.Flags().Changed("cpus"), o.cpus),
		CderunCPUs:            optFloat(cmd.Flags().Changed("cderun-cpus"), o.cderunCPUs),
		Devices:               o.devices,
		CderunDevices:         o.cderunDevices,
		Diagnosis:             optBool(cmd.Flags().Changed("diagnosis"), o.diagnosis),
		CderunDiagnosis:       optBool(cmd.Flags().Changed("cderun-diagnosis"), o.cderunDiagnosis),
		DiagnosisFormat:       optStr(cmd.Flags().Changed("diagnosis-format"), o.diagnosisFormat),
		CderunDiagnosisFormat: optStr(cmd.Flags().Changed("cderun-diagnosis-format"), o.cderunDiagnosisFormat),
		DNS:                   o.dns,
		CderunDNS:             o.cderunDNS,
		DryRun:                optBool(cmd.Flags().Changed("dry-run"), o.dryRun),
		CderunDryRun:          optBool(cmd.Flags().Changed("cderun-dry-run"), o.cderunDryRun),
		DryRunFormat:          optStr(cmd.Flags().Changed("dry-run-format"), o.dryRunFormat),
		CderunDryRunFormat:    optStr(cmd.Flags().Changed("cderun-dry-run-format"), o.cderunDryRunFormat),
		Entrypoint:            o.entrypoint,
		CderunEntrypoint:      o.cderunEntrypoint,
		Env:                   o.env,
		CderunEnv:             o.cderunEnv,
		Expose:                o.expose,
		CderunExpose:          o.cderunExpose,
		GroupAdd:              o.groupAdd,
		CderunGroupAdd:        o.cderunGroupAdd,
		HangTimeout:           optStr(cmd.Flags().Changed("hang-timeout"), o.hangTimeout),
		CderunHangTimeout:     optStr(cmd.Flags().Changed("cderun-hang-timeout"), o.cderunHangTimeout),
		Hostname:              optStr(cmd.Flags().Changed("hostname"), o.hostname),
		CderunHostname:        optStr(cmd.Flags().Changed("cderun-hostname"), o.cderunHostname),
		Image:                 optStr(cmd.Flags().Changed("image"), o.image),
		CderunImage:           optStr(cmd.Flags().Changed("cderun-image"), o.cderunImage),
		Init:                  optBool(cmd.Flags().Changed("init"), o.init),
		CderunInit:            optBool(cmd.Flags().Changed("cderun-init"), o.cderunInit),
		Interactive:           optBool(cmd.Flags().Changed("interactive"), o.interactive),
		CderunInteractive:     optBool(cmd.Flags().Changed("cderun-interactive"), o.cderunInteractive),
		Ipc:                   optStr(cmd.Flags().Changed("ipc"), o.ipc),
		CderunIpc:             optStr(cmd.Flags().Changed("cderun-ipc"), o.cderunIpc),
		LogFormat:             optStr(cmd.Flags().Changed("log-format"), o.logFormat),
		CderunLogFormat:       optStr(cmd.Flags().Changed("cderun-log-format"), o.cderunLogFormat),
		LogLevel:              optStr(cmd.Flags().Changed("log-level"), o.logLevel),
		CderunLogLevel:        optStr(cmd.Flags().Changed("cderun-log-level"), o.cderunLogLevel),
		LogTimestamp:          optBool(cmd.Flags().Changed("log-timestamp"), o.logTimestamp),
		CderunLogTimestamp:    optBool(cmd.Flags().Changed("cderun-log-timestamp"), o.cderunLogTimestamp),
		Memory:                optStr(cmd.Flags().Changed("memory"), o.memory),
		CderunMemory:          optStr(cmd.Flags().Changed("cderun-memory"), o.cderunMemory),
		Mounts:                o.mounts,
		CderunMounts:          o.cderunMounts,
		MountAllTools:         optBool(cmd.Flags().Changed("mount-all-tools"), o.mountAllTools),
		CderunMountAllTools:   optBool(cmd.Flags().Changed("cderun-mount-all-tools"), o.cderunMountAllTools),
		MountCderun:           optBool(cmd.Flags().Changed("mount-cderun"), o.mountCderun),
		CderunMountCderun:     optBool(cmd.Flags().Changed("cderun-mount-cderun"), o.cderunMountCderun),
		MountCderunPath:       optStr(cmd.Flags().Changed("mount-cderun-path"), o.mountCderunPath),
		CderunMountCderunPath: optStr(cmd.Flags().Changed("cderun-mount-cderun-path"), o.cderunMountCderunPath),
		MountSocket:           optBool(cmd.Flags().Changed("mount-socket"), o.mountSocket),
		CderunMountSocket:     optBool(cmd.Flags().Changed("cderun-mount-socket"), o.cderunMountSocket),
		MountSocketPath:       optStr(cmd.Flags().Changed("mount-socket-path"), o.mountSocketPath),
		CderunMountSocketPath: optStr(cmd.Flags().Changed("cderun-mount-socket-path"), o.cderunMountSocketPath),
		MountTools:            optStr(cmd.Flags().Changed("mount-tools"), o.mountTools),
		CderunMountTools:      optStr(cmd.Flags().Changed("cderun-mount-tools"), o.cderunMountTools),
		Network:               optStr(cmd.Flags().Changed("network"), o.network),
		CderunNetwork:         optStr(cmd.Flags().Changed("cderun-network"), o.cderunNetwork),
		Pid:                   optStr(cmd.Flags().Changed("pid"), o.pid),
		CderunPid:             optStr(cmd.Flags().Changed("cderun-pid"), o.cderunPid),
		Privileged:            optBool(cmd.Flags().Changed("privileged"), o.privileged),
		CderunPrivileged:      optBool(cmd.Flags().Changed("cderun-privileged"), o.cderunPrivileged),
		Ports:                 o.ports,
		CderunPorts:           o.cderunPorts,
		PublishAll:            optBool(cmd.Flags().Changed("publish-all"), o.publishAll),
		CderunPublishAll:      optBool(cmd.Flags().Changed("cderun-publish-all"), o.cderunPublishAll),
		Pull:                  optStr(cmd.Flags().Changed("pull"), o.pull),
		CderunPull:            optStr(cmd.Flags().Changed("cderun-pull"), o.cderunPull),
		PullBackoffBase:       optStr(cmd.Flags().Changed("pull-backoff-base"), o.pullBackoffBase),
		CderunPullBackoffBase: optStr(cmd.Flags().Changed("cderun-pull-backoff-base"), o.cderunPullBackoffBase),
		PullMaxRetries:        optInt(cmd.Flags().Changed("pull-max-retries"), o.pullMaxRetries),
		CderunPullMaxRetries:  optInt(cmd.Flags().Changed("cderun-pull-max-retries"), o.cderunPullMaxRetries),
		ReadOnly:              optBool(cmd.Flags().Changed("read-only"), o.readOnly),
		CderunReadOnly:        optBool(cmd.Flags().Changed("cderun-read-only"), o.cderunReadOnly),
		Remove:                optBool(cmd.Flags().Changed("remove"), o.remove),
		CderunRemove:          optBool(cmd.Flags().Changed("cderun-remove"), o.cderunRemove),
		Runtime:               optStr(cmd.Flags().Changed("runtime"), o.runtime),
		CderunRuntime:         optStr(cmd.Flags().Changed("cderun-runtime"), o.cderunRuntime),
		SensitiveEnv:          o.sensitiveEnv,
		CderunSensitiveEnv:    o.cderunSensitiveEnv,
		SocketPath:            optStr(cmd.Flags().Changed("socket-path"), o.socketPath),
		CderunSocketPath:      optStr(cmd.Flags().Changed("cderun-socket-path"), o.cderunSocketPath),
		StrictEnv:             optBool(cmd.Flags().Changed("strict-env"), o.strictEnv),
		CderunStrictEnv:       optBool(cmd.Flags().Changed("cderun-strict-env"), o.cderunStrictEnv),
		Sysctls:               o.sysctls,
		CderunSysctls:         o.cderunSysctls,
		ToolConfig:            optStr(cmd.Flags().Changed("tool-config"), o.toolConfig),
		CderunToolConfig:      optStr(cmd.Flags().Changed("cderun-tool-config"), o.cderunToolConfig),
		TTY:                   optBool(cmd.Flags().Changed("tty"), o.tty),
		CderunTTY:             optBool(cmd.Flags().Changed("cderun-tty"), o.cderunTTY),
		Ulimits:               o.ulimits,
		CderunUlimits:         o.cderunUlimits,
		User:                  optStr(cmd.Flags().Changed("user"), o.user),
		CderunUser:            optStr(cmd.Flags().Changed("cderun-user"), o.cderunUser),
		Workdir:               optStr(cmd.Flags().Changed("workdir"), o.workdir),
		CderunWorkdir:         optStr(cmd.Flags().Changed("cderun-workdir"), o.cderunWorkdir),
	}
}

func getBoolPointers(o *rootOptions, name string) (base, override *bool) {
	switch name {
	case "diagnosis":
		return &o.diagnosis, &o.cderunDiagnosis
	case "dry-run":
		return &o.dryRun, &o.cderunDryRun
	case "init":
		return &o.init, &o.cderunInit
	case "interactive":
		return &o.interactive, &o.cderunInteractive
	case "log-timestamp":
		return &o.logTimestamp, &o.cderunLogTimestamp
	case "mount-all-tools":
		return &o.mountAllTools, &o.cderunMountAllTools
	case "mount-cderun":
		return &o.mountCderun, &o.cderunMountCderun
	case "mount-socket":
		return &o.mountSocket, &o.cderunMountSocket
	case "privileged":
		return &o.privileged, &o.cderunPrivileged
	case "publish-all":
		return &o.publishAll, &o.cderunPublishAll
	case "read-only":
		return &o.readOnly, &o.cderunReadOnly
	case "remove":
		return &o.remove, &o.cderunRemove
	case "strict-env":
		return &o.strictEnv, &o.cderunStrictEnv
	case "tty":
		return &o.tty, &o.cderunTTY
	default:
		return nil, nil
	}
}

func getStringPointers(o *rootOptions, name string) (base, override *string) {
	switch name {
	case "config":
		return &o.config, &o.cderunConfig
	case "diagnosis-format":
		return &o.diagnosisFormat, &o.cderunDiagnosisFormat
	case "dry-run-format":
		return &o.dryRunFormat, &o.cderunDryRunFormat
	case "hang-timeout":
		return &o.hangTimeout, &o.cderunHangTimeout
	case "hostname":
		return &o.hostname, &o.cderunHostname
	case "image":
		return &o.image, &o.cderunImage
	case "ipc":
		return &o.ipc, &o.cderunIpc
	case "log-format":
		return &o.logFormat, &o.cderunLogFormat
	case "log-level":
		return &o.logLevel, &o.cderunLogLevel
	case "memory":
		return &o.memory, &o.cderunMemory
	case "mount-cderun-path":
		return &o.mountCderunPath, &o.cderunMountCderunPath
	case "mount-socket-path":
		return &o.mountSocketPath, &o.cderunMountSocketPath
	case "mount-tools":
		return &o.mountTools, &o.cderunMountTools
	case "network":
		return &o.network, &o.cderunNetwork
	case "pid":
		return &o.pid, &o.cderunPid
	case "pull":
		return &o.pull, &o.cderunPull
	case "pull-backoff-base":
		return &o.pullBackoffBase, &o.cderunPullBackoffBase
	case "runtime":
		return &o.runtime, &o.cderunRuntime
	case "socket-path":
		return &o.socketPath, &o.cderunSocketPath
	case "tool-config":
		return &o.toolConfig, &o.cderunToolConfig
	case "user":
		return &o.user, &o.cderunUser
	case "workdir":
		return &o.workdir, &o.cderunWorkdir
	default:
		return nil, nil
	}
}

func getIntPointers(o *rootOptions, name string) (base, override *int) {
	switch name {
	case "pull-max-retries":
		return &o.pullMaxRetries, &o.cderunPullMaxRetries
	default:
		return nil, nil
	}
}

func getFloat64Pointers(o *rootOptions, name string) (base, override *float64) {
	switch name {
	case "cpus":
		return &o.cpus, &o.cderunCPUs
	default:
		return nil, nil
	}
}

func getStringSlicePointers(o *rootOptions, name string) (base, override *[]string) {
	switch name {
	case "add-host":
		return &o.addHosts, &o.cderunAddHosts
	case "cap-add":
		return &o.capAdd, &o.cderunCapAdd
	case "cap-drop":
		return &o.capDrop, &o.cderunCapDrop
	case "device":
		return &o.devices, &o.cderunDevices
	case "dns":
		return &o.dns, &o.cderunDNS
	case "entrypoint":
		return &o.entrypoint, &o.cderunEntrypoint
	case "env":
		return &o.env, &o.cderunEnv
	case "expose":
		return &o.expose, &o.cderunExpose
	case "group-add":
		return &o.groupAdd, &o.cderunGroupAdd
	case "mount":
		return &o.mounts, &o.cderunMounts
	case "publish":
		return &o.ports, &o.cderunPorts
	case "sensitive-env":
		return &o.sensitiveEnv, &o.cderunSensitiveEnv
	case "sysctl":
		return &o.sysctls, &o.cderunSysctls
	case "ulimit":
		return &o.ulimits, &o.cderunUlimits
	default:
		return nil, nil
	}
}
